version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
  metabase:
    image: metabase/metabase:latest
    ports:
      - 3000:3000
    env_file:
      - .env
  mysql:
    image: mysql:8.0
    volumes:
      - ./docker/mysql/seeds:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db-data:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
