version: "3.8"

services:
  metabase:
    image: metabase/metabase:latest
    ports:
      - 3000:3000
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
